dataset:
  format: precompute_wide_resnet50_2
  name: cifar10
  category: cifar10_vs_svhn
  train_size: 100
  test_size: 100
  train_dataset_path: /workspaces/ood/data/feature_maps/cifar10train_wide_resnet50_layer2_layer3_layer4_1000_img_per_class.npy
  test_dataset_in_path: /workspaces/ood/data/feature_maps/cifar10test_wide_resnet50_layer2_layer3_layer4_100_img_per_class.npy
  test_dataset_out_path: /workspaces/ood/data/feature_maps/svhntest_wide_resnet50_layer2_layer3_layer4_100_img_per_class.npy
  image_size: 256
  create_validation_set: False
  train_batch_size: 8
  test_batch_size: 8
  inference_batch_size: 8
  fiber_batch_size: 64
  num_workers: 12

model:
  name: fastflow
  backbone: wide_resnet50_2
  layers:
    - layer2
    - layer3
    - layer4
  pool_dims:
    - [512, 28, 28]
    - [1024, 14, 14]
    - [2048, 7, 7]
  decoder: freia-cflow
  condition_vector: 128
  coupling_blocks: 4
  clamp_alpha: 1.9
  lr: 0.000001
  early_stopping:
    patience: 2
    metric: image_AUROC 
    mode: max
  normalization_method: min_max # options: [null, min_max, cdf]
  threshold:
    image_default: 0
    pixel_default: 0
    adaptive: true

project:
  seed: 0
  path: ./results
  log_images_to: []
  logger: false #wandb
  save_to_csv: true #false

# PL Trainer Args. Don't add extra parameter here.
trainer:
  accelerator: null
  accumulate_grad_batches: 1
  amp_backend: apex
  amp_level: O2
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 2
  checkpoint_callback: true
  default_root_dir: null
  deterministic: false
  fast_dev_run: false
  flush_logs_every_n_steps: 100
  gpus: 1
  gradient_clip_val: 0
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  log_gpu_memory: null
  max_epochs: 5
  max_steps: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: 1
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  prepare_data_per_node: true
  process_position: 0
  profiler: null
  progress_bar_refresh_rate: null
  reload_dataloaders_every_epoch: false
  replace_sampler_ddp: true
  stochastic_weight_avg: false
  sync_batchnorm: false
  terminate_on_nan: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: 1.0
  weights_save_path: null
  weights_summary: top
